/**
 * The code sets up an Express server for an email service that sends OTP and password reset emails
 * using Firebase Admin SDK and a third-party email service, with periodic cleanup of expired OTPs.
 * @param emailHash - The `emailHash` is a hashed version of the email address used as a key for
 * storing and retrieving data related to that email address. In the provided code, the `emailHash` is
 * generated by replacing certain characters in the email address with underscores to create a valid
 * key for Firebase Realtime Database
 * @param [ttlMs] - The `ttlMs` parameter stands for "time to live in milliseconds". It is used to
 * specify the duration for which a certain operation or data should remain valid or active before
 * expiring or being automatically removed. In the context of the code you provided, `ttlMs` is often
 * used to set
 * @returns The code provided is a Node.js application that sets up an Express server to handle
 * email-related functionalities such as sending OTP emails and password reset emails. It integrates
 * with Firebase Admin SDK for database operations and email sending via Brevo API or a mock
 * implementation if the API key is not provided.
 */
const express = require('express');
const Brevo = require('@getbrevo/brevo');
const cors = require('cors');
const admin = require('firebase-admin');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 3000;

// Initialize Firebase Admin
let adminInitialized = false;
let mockDb = {
/**
 * A mock Firebase Realtime Database reference object that can be used to test code that normally
 * interacts with Firebase Realtime Database. The object provides methods to simulate reading, writing, and
 * deleting data from the database, but does not actually interact with the database.
 * @param {string} path - The path to the location in the database that the reference object should
 * point to.
 * @returns {Object} - A mock Firebase Realtime Database reference object.
 */
  ref: (path) => ({
    once: () => Promise.resolve({ val: () => ({}) }),
    set: () => Promise.resolve(),
    remove: () => Promise.resolve()
  })
};

const mockAdminAuth = {
/**
 * Mock Firebase Admin Auth object for testing purposes.
 * 
 * @returns {Object} - An object with a single method, `generatePasswordResetLink`, which generates a mock
 * password reset link for a given email address.
 */
/**
 * Generates a mock password reset link for a given email address.
 * 
 * @param {string} email - The email address for which the password reset link should be generated.
 * @param {Object} settings - Settings for generating the password reset link.
 * @returns {Promise<string>} - A promise that resolves with the mock password reset link.
 */
  auth: () => ({
/**
 * Generates a mock password reset link for a given email address.
 *
 * @param {string} email - The email address for which the password reset link should be generated.
 * @param {Object} settings - Settings for generating the password reset link.
 * @returns {Promise<string>} - A promise that resolves with the mock password reset link.
 */
    generatePasswordResetLink: async (email, settings) => {
      console.log(`Mock: Generated password reset link for ${email}`);
      return `https://example.com/reset-password?email=${encodeURIComponent(email)}`;
    }
  })
};

try {
  if (process.env.FIREBASE_PRIVATE_KEY && process.env.FIREBASE_CLIENT_EMAIL) {
    // Handle different private key formats
    let privateKey = process.env.FIREBASE_PRIVATE_KEY;
    
    // If the key doesn't have newlines, try to add them
    if (!privateKey.includes('\n') && privateKey.includes('\\n')) {
      privateKey = privateKey.replace(/\\n/g, '\n');
    }
    
    // Remove any quotes that might have been added
    privateKey = privateKey.replace(/^["']|["']$/g, '');
    
    console.log('🔧 Firebase key format check:', {
      hasNewlines: privateKey.includes('\n'),
      startsWithBegin: privateKey.startsWith('-----BEGIN'),
      length: privateKey.length
    });
    
    const serviceAccount = {
      type: process.env.FIREBASE_TYPE || 'service_account',
      project_id: process.env.FIREBASE_PROJECT_ID,
      private_key_id: process.env.FIREBASE_PRIVATE_KEY_ID,
      private_key: privateKey,
      client_email: process.env.FIREBASE_CLIENT_EMAIL,
      client_id: process.env.FIREBASE_CLIENT_ID,
      auth_uri: process.env.FIREBASE_AUTH_URI || 'https://accounts.google.com/o/oauth2/auth',
      token_uri: process.env.FIREBASE_TOKEN_URI || 'https://oauth2.googleapis.com/token',
      auth_provider_x509_cert_url: process.env.FIREBASE_AUTH_PROVIDER_X509_CERT_URL || 'https://www.googleapis.com/oauth2/v1/certs',
      client_x509_cert_url: process.env.FIREBASE_CLIENT_X509_CERT_URL
    };

    admin.initializeApp({
      credential: admin.credential.cert(serviceAccount),
      databaseURL: process.env.FIREBASE_DATABASE_URL
    });
    
    adminInitialized = true;
    console.log('✅ Firebase Admin SDK initialized successfully');
  } else {
    console.log('⚠️ Firebase Admin SDK credentials not found, using mock implementation');
  }
} catch (error) {
  console.error('❌ Failed to initialize Firebase Admin SDK:', error.message);
  console.error('❌ Error code:', error.code);
  console.log('⚠️ Using mock implementation instead');
}

const db = adminInitialized ? admin.database() : mockDb;

if (!adminInitialized) {
  admin.auth = () => mockAdminAuth.auth();
}

// Middleware
app.use(cors());
app.use(express.json());

// Initialize Brevo client
let brevoClient;
let brevoReady = false;

const otpSendLocks = new Map();
const localDistributedLocks = new Map();

/**
 * Acquires an OTP lock for the given email hash, either using a distributed lock via Firebase Realtime Database
 * or a local lock if the Firebase Realtime Database is not available.
 * If the lock is acquired, the function returns true, otherwise false.
 * The lock is valid for the specified duration in milliseconds.
 * If a lock already exists, the lock is not re-acquired and the function returns false.
 * @param {string} emailHash - The email hash for which the lock should be acquired.
 * @param {number} [ttlMs] - The duration in milliseconds for which the lock should remain valid. Defaults to 15 seconds.
 * @returns {Promise<boolean>} - A promise that resolves with true if the lock was acquired, otherwise false.
 */
async function acquireOtpLock(emailHash, ttlMs = 15 * 1000) {
  const now = Date.now();
  
  // Skip Firebase lock in serverless - use local only for speed
  if (process.env.VERCEL || process.env.NODE_ENV === 'production') {
    const existing = localDistributedLocks.get(emailHash) || 0;
    if (existing > now) return false;
    localDistributedLocks.set(emailHash, now + ttlMs);
    return true;
  }
  
  try {
    if (adminInitialized && db && typeof db.ref === 'function') {
      const lockRef = db.ref(`otpLocks/${emailHash}`);
      if (typeof lockRef.transaction === 'function') {
        const result = await Promise.race([
          lockRef.transaction((current) => {
            if (!current || !current.expiresAt || current.expiresAt < now) {
              return { expiresAt: now + ttlMs };
            }
            return;
          }),
          new Promise((_, reject) => setTimeout(() => reject(new Error('Lock timeout')), 3000))
        ]);
        const committed = result && (result.committed === true || (result.snapshot && result.snapshot.exists()));
        const val = result && result.snapshot && result.snapshot.val ? result.snapshot.val() : undefined;
        const hasLock = committed && val && val.expiresAt && val.expiresAt > now;
        if (hasLock) return true;
        return false;
      }
    }
  } catch (e) {
    console.warn('⚠️ Failed to acquire distributed lock via Firebase, falling back to local lock.', e);
  }
  const existing = localDistributedLocks.get(emailHash) || 0;
  if (existing > now) return false;
  localDistributedLocks.set(emailHash, now + ttlMs);
  return true;
}

/**
 * Releases an OTP lock for the given email hash.
 * If a distributed lock was used, this function attempts to delete the lock from the Firebase Realtime Database.
 * If the deletion fails (e.g. due to a network error), a warning is logged and the lock is allowed to expire naturally.
 * Additionally, the local lock is deleted.
 * @param {string} emailHash - The email hash for which the lock should be released.
 */
async function releaseOtpLock(emailHash) {
  try {
    if (adminInitialized && db && typeof db.ref === 'function') {
      const lockRef = db.ref(`otpLocks/${emailHash}`);
      await lockRef.remove();
    }
  } catch (e) {
    console.warn('⚠️ Failed to release distributed lock. It will expire naturally.', e);
  }
  localDistributedLocks.delete(emailHash);
}

if (process.env.BREVO_API_KEY) {
  try {
    console.log('🔧 Initializing Brevo with key:', process.env.BREVO_API_KEY.substring(0, 20) + '...');
    brevoClient = new Brevo.TransactionalEmailsApi();
    brevoClient.setApiKey(Brevo.TransactionalEmailsApiApiKeys.apiKey, process.env.BREVO_API_KEY);
    brevoReady = true;
    console.log('✅ Brevo client initialized');
    console.log('📧 Sender email:', process.env.BREVO_SENDER_EMAIL);
  } catch (error) {
    console.error('❌ Failed to initialize Brevo client:', error.message);
  }
} else {
  console.log('⚠️ BREVO_API_KEY not set, using mock email sender');
}

/**
 * Sends an email using Brevo or a mock email sender.
 * If a Brevo client is available (i.e. BREVO_API_KEY is set), the email is sent using Brevo.
 * Otherwise, a mock email sender is used.
 * @param {Object} options - The email options.
 * @param {string} options.to - The recipient email address.
 * @param {string} options.subject - The email subject.
 * @param {string} [options.html] - The email HTML content.
 * @param {string} [options.text] - The email text content.
 * @returns {Promise<Object>} - A promise that resolves with the email response.
 * @throws {Error} - If the Brevo API throws an error.
 */
async function sendEmail({ to, subject, html, text }) {
  if (brevoReady && brevoClient) {
    try {
      const sendSmtpEmail = {
        sender: {
          email: process.env.BREVO_SENDER_EMAIL || 'no-reply@nexus.local',
          name: process.env.BREVO_SENDER_NAME || 'Nexus'
        },
        to: [{ email: to }],
        subject,
        htmlContent: html,
        textContent: text
      };
      console.log('📧 Sending email via Brevo to:', to);
      
      // Add timeout for Brevo API call
      const resp = await Promise.race([
        brevoClient.sendTransacEmail(sendSmtpEmail),
        new Promise((_, reject) => 
          setTimeout(() => reject(new Error('Brevo API timeout after 10s')), 10000)
        )
      ]);
      
      console.log('✅ Brevo response:', resp);
      return resp;
    } catch (error) {
      console.error('❌ Brevo API error:', error);
      console.error('❌ Error details:', error.message);
      throw error;
    }
  }
  console.log('📧 MOCK EMAIL SENDING:');
  console.log('   To:', to);
  console.log('   Subject:', subject);
  console.log('   Text:', text ? String(text).substring(0, 100) + '...' : 'No text content');
  return { messageId: 'mock-message-id-' + Date.now(), response: 'Mock email sent successfully' };
}

/**
 * Generates a unique 6-digit OTP by checking against existing OTPs in the Firebase Realtime Database.
 * If a unique OTP cannot be generated within 5 attempts, a new random OTP is generated and returned.
 * If the Firebase Realtime Database is not available, a new random OTP is generated and returned.
 * @returns {Promise<string>} - A promise that resolves with a unique 6-digit OTP.
 */
async function generateUniqueOtp() {
  const generate = () => String(Math.floor(100000 + Math.random() * 900000));

  if (!adminInitialized || !db || typeof db.ref !== 'function') {
    return generate();
  }

  for (let i = 0; i < 5; i++) {
    const otp = generate();
    try {
      const snapshot = await db.ref('otp').once('value');
      const all = snapshot && typeof snapshot.val === 'function' ? snapshot.val() : snapshot?.val;
      const existing = typeof all === 'function' ? all() : all;
      const isUsed = existing
        ? Object.values(existing).some((entry) => entry && String(entry.otp) === otp)
        : false;
      if (!isUsed) return otp;
    } catch (e) {
      return otp;
    }
  }
  return generate();
}

// Health check endpoint
app.get('/', (req, res) => {
  res.json({
    status: 'OK',
    message: 'Nexus Email Service is running',
    timestamp: new Date().toISOString()
  });
});

// Diagnostic endpoint (for debugging only - remove in production)
app.get('/debug', (req, res) => {
  res.json({
    brevoConfigured: brevoReady,
    firebaseConfigured: adminInitialized,
    environment: process.env.NODE_ENV || 'development',
    hasBrevoKey: !!process.env.BREVO_API_KEY,
    hasFirebaseKey: !!process.env.FIREBASE_PRIVATE_KEY,
    senderEmail: process.env.BREVO_SENDER_EMAIL || 'not set'
  });
});

// Send OTP email endpoint
/* The above code is a JavaScript function that handles a POST request to send an OTP (One-Time
Password) via email. Here is a breakdown of the main functionalities: */
app.post('/send-otp', async (req, res) => {
  const startTime = Date.now();
  try {
    console.log('📨 Received OTP request at', new Date().toISOString());
    const { email } = req.body;
    
    if (!email) {
      console.log('❌ No email provided');
      return res.status(400).json({
        success: false,
        error: 'Email is required'
      });
    }
    
    console.log('📧 Processing OTP for:', email);
    console.log('🔧 Brevo ready:', brevoReady, 'Firebase ready:', adminInitialized);
    
    const emailHash = email.replace(/[.#$[\]]/g, '_');
    const otpRef = db.ref(`otp/${emailHash}`);
    const RATE_LIMIT_MS = 60 * 1000;

    const now = Date.now();
    const lastSendMs = otpSendLocks.get(emailHash) || 0;
    if (now - lastSendMs < RATE_LIMIT_MS) {
      console.log(`⏱️ Rate-limited OTP request for ${email}`);
      return res.json({
        success: true,
        message: 'OTP already sent recently. Please check your inbox.',
        rateLimited: true
      });
    }

    console.log('🔒 Acquiring lock...');
    const gotLock = await acquireOtpLock(emailHash);
    if (!gotLock) {
      console.log(`🔒 Another OTP request is in progress for ${email}`);
      return res.json({ success: true, message: 'OTP already in progress.', inProgress: true });
    }
    console.log('✅ Lock acquired');

    let existing = null;
    try {
      console.log('📖 Reading existing OTP from Firebase...');
      const snap = await Promise.race([
        otpRef.once('value'),
        new Promise((_, reject) => setTimeout(() => reject(new Error('Firebase read timeout')), 5000))
      ]);
      existing = snap && typeof snap.val === 'function' ? snap.val() : snap?.val;
      console.log('✅ Firebase read complete');
    } catch (e) {
      console.warn('⚠️ Could not read existing OTP', e.message);
    }

    let otp;
    const ttlMs = 5 * 60 * 1000;
    const nowMs = Date.now();
    if (existing && existing.expiresAt && existing.expiresAt > nowMs && existing.otp) {
      otp = String(existing.otp);
      console.log(`♻️ Reusing existing unexpired OTP for ${email}`);
    } else {
      otp = await generateUniqueOtp();
      console.log(`🔐 Generated unique OTP: ${otp} for ${email}`);
    }

    console.log('💾 Storing OTP in Firebase...');
    try {
      await Promise.race([
        otpRef.set({
          email: email,
          otp: otp,
          expiresAt: nowMs + ttlMs,
          attempts: existing?.attempts ?? 0,
          sentAt: nowMs,
          generatedAt: existing?.generatedAt ?? nowMs
        }),
        new Promise((_, reject) => setTimeout(() => reject(new Error('Firebase write timeout')), 5000))
      ]);
      console.log('✅ OTP stored successfully in Firebase');
    } catch (firebaseError) {
      console.error('❌ Error storing OTP in Firebase:', firebaseError.message);
      // Continue anyway - we can still send the email
    }
    
    // Nexus-themed email template with golden accents
    const subject = '🔐 Your Nexus Verification Code';
    const html = `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #000; color: #fff;">
        <!-- Header -->
        <div style="text-align: center; margin-bottom: 40px; padding: 30px 20px; background: linear-gradient(135deg, rgba(251, 191, 36, 0.1) 0%, rgba(0, 0, 0, 0) 100%); border-radius: 12px; border: 1px solid rgba(251, 191, 36, 0.2);">
          <div style="display: inline-block; position: relative;">
            <h1 style="background: linear-gradient(135deg, #fff 0%, #fbbf24 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; margin: 0; font-size: 32px; font-weight: 700; letter-spacing: 2px;">NEXUS</h1>
            <div style="width: 8px; height: 8px; background: #fbbf24; border-radius: 50%; position: absolute; top: 8px; right: -12px; box-shadow: 0 0 10px rgba(251, 191, 36, 0.5); animation: pulse 2s ease-in-out infinite;"></div>
          </div>
          <p style="color: rgba(255, 255, 255, 0.6); margin: 10px 0 0 0; font-size: 14px; letter-spacing: 1px;">VERIFICATION CODE</p>
        </div>
        
        <!-- OTP Card -->
        <div style="background: rgba(17, 17, 17, 0.8); backdrop-filter: blur(10px); border: 2px solid rgba(251, 191, 36, 0.3); border-radius: 16px; padding: 40px 30px; text-align: center; margin: 30px 0; box-shadow: 0 8px 32px rgba(251, 191, 36, 0.1);">
          <h2 style="color: #fbbf24; margin: 0 0 25px 0; font-size: 20px; font-weight: 600; letter-spacing: 0.5px;">Your Verification Code</h2>
          
          <!-- OTP Display -->
          <div style="background: linear-gradient(135deg, rgba(0, 0, 0, 0.6) 0%, rgba(17, 17, 17, 0.6) 100%); border: 2px solid rgba(251, 191, 36, 0.4); border-radius: 12px; padding: 25px 20px; margin: 25px 0; position: relative; overflow: hidden;">
            <div style="position: absolute; top: 0; left: 0; right: 0; height: 1px; background: linear-gradient(90deg, transparent, #fbbf24, transparent);"></div>
            <span style="font-size: 42px; font-weight: 700; color: #fbbf24; letter-spacing: 12px; font-family: 'Courier New', monospace; text-shadow: 0 0 20px rgba(251, 191, 36, 0.3);">${otp}</span>
            <div style="position: absolute; bottom: 0; left: 0; right: 0; height: 1px; background: linear-gradient(90deg, transparent, #fbbf24, transparent);"></div>
          </div>
          
          <!-- Expiry Warning -->
          <div style="background: rgba(251, 191, 36, 0.1); border: 1px solid rgba(251, 191, 36, 0.3); border-radius: 8px; padding: 15px; margin-top: 25px;">
            <p style="color: #fbbf24; margin: 0; font-size: 14px; font-weight: 500;">
              ⚠️ This code will expire in <strong>5 minutes</strong>
            </p>
          </div>
        </div>
        
        <!-- Security Notice -->
        <div style="margin-top: 35px; padding: 25px; background: rgba(17, 17, 17, 0.6); border-radius: 12px; border: 1px solid rgba(255, 255, 255, 0.1);">
          <p style="color: rgba(255, 255, 255, 0.7); margin: 0; font-size: 14px; line-height: 1.6;">
            <strong style="color: #fbbf24;">Security Notice:</strong><br>
            If you didn't request this verification code, please ignore this email. This code is for your Nexus account verification and should not be shared with anyone.
          </p>
        </div>
        
        <!-- Footer -->
        <div style="text-align: center; margin-top: 40px; padding-top: 25px; border-top: 1px solid rgba(251, 191, 36, 0.2);">
          <p style="color: rgba(255, 255, 255, 0.5); margin: 0 0 8px 0; font-size: 13px; letter-spacing: 0.5px;">
            <strong style="color: #fbbf24;">NEXUS</strong> TEAM
          </p>
          <p style="color: rgba(255, 255, 255, 0.4); margin: 0; font-size: 12px;">
            Parental Control Dashboard
          </p>
        </div>
      </div>
    `;
    const text = `
NEXUS - Verification Code

Your verification code is: ${otp}

This code will expire in 5 minutes.

If you didn't request this code, please ignore this email.

Best regards,
Nexus Team
    `;
    
    otpSendLocks.set(emailHash, nowMs);
    let info;
    try {
      console.log('📧 Calling sendEmail function...');
      console.log('📧 Email config - Brevo ready:', brevoReady, 'Sender:', process.env.BREVO_SENDER_EMAIL);
      
      info = await Promise.race([
        sendEmail({ to: email, subject, html, text }),
        new Promise((_, reject) => 
          setTimeout(() => reject(new Error('Email send timeout after 15s')), 15000)
        )
      ]);
      
      console.log('✅ sendEmail completed:', JSON.stringify(info).substring(0, 200));
    } catch (emailError) {
      console.error('❌ sendEmail failed:', emailError.message);
      console.error('❌ Error stack:', emailError.stack);
      throw emailError;
    } finally {
      await releaseOtpLock(emailHash);
      console.log('🔓 Lock released');
    }
    
    const messageId = (info && (info.messageId || (info.messageIds && info.messageIds[0]))) || 'unknown';
    const elapsed = Date.now() - startTime;
    console.log(`✅ Email sent successfully in ${elapsed}ms. Message ID:`, messageId);
    
    res.json({
      success: true,
      messageId: messageId,
      message: 'OTP email sent successfully'
    });
    
  } catch (error) {
    console.error('❌ Error sending email:', error);
    console.error('❌ Error stack:', error.stack);
    res.status(500).json({
      success: false,
      error: 'Failed to send email',
      details: error.message
    });
  }
});

// Verify OTP endpoint
app.post('/verify-otp', async (req, res) => {
  try {
    console.log('🔍 Received OTP verification request');
    const { email, otp } = req.body;
    
    if (!email || !otp) {
      console.log('❌ Missing email or OTP');
      return res.status(400).json({
        success: false,
        error: 'Email and OTP are required'
      });
    }
    
    console.log('🔐 Verifying OTP for:', email);
    
    const emailHash = email.replace(/[.#$[\]]/g, '_');
    const otpRef = db.ref(`otp/${emailHash}`);
    
    let existing = null;
    try {
      const snap = await otpRef.once('value');
      existing = snap && typeof snap.val === 'function' ? snap.val() : snap?.val;
    } catch (e) {
      console.error('❌ Error reading OTP from Firebase:', e);
      return res.status(500).json({
        success: false,
        error: 'Failed to verify OTP'
      });
    }
    
    // Check if OTP exists
    if (!existing || !existing.otp) {
      console.log('❌ No OTP found for email:', email);
      return res.status(400).json({
        success: false,
        error: 'No OTP found. Please request a new one.'
      });
    }
    
    // Check if OTP has expired
    const now = Date.now();
    if (existing.expiresAt <= now) {
      console.log('⏰ OTP expired for:', email);
      // Remove expired OTP
      await otpRef.remove();
      return res.status(400).json({
        success: false,
        error: 'OTP has expired. Please request a new one.',
        expired: true
      });
    }
    
    // Check if OTP matches
    if (String(existing.otp) === String(otp)) {
      console.log('✅ OTP verified successfully for:', email);
      
      // Consume the OTP (remove it from database)
      await otpRef.remove();
      console.log('🗑️ OTP consumed and removed from database');
      
      return res.json({
        success: true,
        message: 'OTP verified successfully'
      });
    } else {
      console.log('❌ Wrong OTP entered for:', email);
      
      // Increment attempt counter
      const attempts = (existing.attempts || 0) + 1;
      const maxAttempts = 5;
      
      if (attempts >= maxAttempts) {
        console.log('🚫 Max attempts reached, expiring OTP immediately');
        // Remove OTP after max attempts
        await otpRef.remove();
        return res.status(400).json({
          success: false,
          error: 'Too many failed attempts. Please request a new OTP.',
          maxAttemptsReached: true
        });
      } else {
        // Update attempt count and expire immediately on wrong OTP
        console.log(`⚠️ Wrong OTP, expiring immediately. Attempt ${attempts}/${maxAttempts}`);
        await otpRef.remove();
        return res.status(400).json({
          success: false,
          error: 'Invalid OTP. Please request a new one.',
          attemptsRemaining: maxAttempts - attempts,
          wrongOtp: true
        });
      }
    }
    
  } catch (error) {
    console.error('❌ Error verifying OTP:', error);
    console.error('❌ Error stack:', error.stack);
    res.status(500).json({
      success: false,
      error: 'Failed to verify OTP',
      details: error.message
    });
  }
});

// Password reset email endpoint
/* The above code is a route handler function in a Node.js application using Express framework. It
handles a POST request to send a password reset email to a user. Here's a breakdown of what the code
does: */
app.post('/send-password-reset', async (req, res) => {
  try {
    const { email, actionUrl } = req.body;
    
    if (!email) {
      return res.status(400).json({
        success: false,
        error: 'Email is required'
      });
    }
    
    console.log(`📧 Processing password reset for: ${email}`);
    
    const actionCodeSettings = {
      url: actionUrl || process.env.FIREBASE_AUTH_DOMAIN || 'https://example.com',
      handleCodeInApp: false
    };
    
    let resetLink;
    try {
      resetLink = await admin.auth().generatePasswordResetLink(email, actionCodeSettings);
      console.log('✅ Generated password reset link for:', email);
    } catch (firebaseError) {
      console.error('❌ Error generating password reset link:', firebaseError);
      resetLink = `${actionUrl || 'https://example.com'}/reset-password?email=${encodeURIComponent(email)}&oobCode=mockCode123`;
      console.log('⚠️ Using mock reset link for testing:', resetLink);
    }
    
    // Nexus-themed password reset email
    const subject = '🔐 Reset Your Nexus Password';
    const html = `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #000; color: #fff;">
        <!-- Header -->
        <div style="text-align: center; margin-bottom: 40px; padding: 30px 20px; background: linear-gradient(135deg, rgba(251, 191, 36, 0.1) 0%, rgba(0, 0, 0, 0) 100%); border-radius: 12px; border: 1px solid rgba(251, 191, 36, 0.2);">
          <div style="display: inline-block; position: relative;">
            <h1 style="background: linear-gradient(135deg, #fff 0%, #fbbf24 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; margin: 0; font-size: 32px; font-weight: 700; letter-spacing: 2px;">NEXUS</h1>
            <div style="width: 8px; height: 8px; background: #fbbf24; border-radius: 50%; position: absolute; top: 8px; right: -12px; box-shadow: 0 0 10px rgba(251, 191, 36, 0.5);"></div>
          </div>
          <p style="color: rgba(255, 255, 255, 0.6); margin: 10px 0 0 0; font-size: 14px; letter-spacing: 1px;">PASSWORD RESET</p>
        </div>
        
        <!-- Reset Card -->
        <div style="background: rgba(17, 17, 17, 0.8); backdrop-filter: blur(10px); border: 2px solid rgba(251, 191, 36, 0.3); border-radius: 16px; padding: 40px 30px; text-align: center; margin: 30px 0; box-shadow: 0 8px 32px rgba(251, 191, 36, 0.1);">
          <h2 style="color: #fbbf24; margin: 0 0 20px 0; font-size: 20px; font-weight: 600;">Reset Your Password</h2>
          <p style="color: rgba(255, 255, 255, 0.8); margin: 20px 0; font-size: 15px; line-height: 1.6;">Click the button below to reset your password:</p>
          
          <!-- Reset Button -->
          <div style="margin: 35px 0;">
            <a href="${resetLink}" style="display: inline-block; background: linear-gradient(135deg, #fbbf24 0%, #f59e0b 100%); color: #000; text-decoration: none; padding: 16px 40px; border-radius: 8px; font-weight: 600; font-size: 15px; letter-spacing: 0.5px; box-shadow: 0 4px 15px rgba(251, 191, 36, 0.3); transition: all 0.3s;">Reset Password</a>
          </div>
          
          <!-- Expiry Warning -->
          <div style="background: rgba(251, 191, 36, 0.1); border: 1px solid rgba(251, 191, 36, 0.3); border-radius: 8px; padding: 15px; margin-top: 25px;">
            <p style="color: #fbbf24; margin: 0; font-size: 14px; font-weight: 500;">
              ⚠️ This link will expire in <strong>1 hour</strong>
            </p>
          </div>
          
          <!-- Alternative Link -->
          <p style="color: rgba(255, 255, 255, 0.7); margin: 25px 0 15px 0; font-size: 13px;">If the button doesn't work, copy and paste this link:</p>
          <div style="background: rgba(0, 0, 0, 0.6); border: 1px solid rgba(251, 191, 36, 0.3); border-radius: 8px; padding: 12px; margin: 15px 0; word-break: break-all;">
            <a href="${resetLink}" style="color: #fbbf24; font-size: 12px; text-decoration: none;">${resetLink}</a>
          </div>
        </div>
        
        <!-- Security Notice -->
        <div style="margin-top: 35px; padding: 25px; background: rgba(17, 17, 17, 0.6); border-radius: 12px; border: 1px solid rgba(255, 255, 255, 0.1);">
          <p style="color: rgba(255, 255, 255, 0.7); margin: 0; font-size: 14px; line-height: 1.6;">
            <strong style="color: #fbbf24;">Security Notice:</strong><br>
            If you didn't request a password reset, please ignore this email or contact support if you have concerns.
          </p>
        </div>
        
        <!-- Footer -->
        <div style="text-align: center; margin-top: 40px; padding-top: 25px; border-top: 1px solid rgba(251, 191, 36, 0.2);">
          <p style="color: rgba(255, 255, 255, 0.5); margin: 0 0 8px 0; font-size: 13px; letter-spacing: 0.5px;">
            <strong style="color: #fbbf24;">NEXUS</strong> TEAM
          </p>
          <p style="color: rgba(255, 255, 255, 0.4); margin: 0; font-size: 12px;">
            Parental Control Dashboard
          </p>
        </div>
      </div>
    `;
    const text = `
NEXUS - Password Reset

Click the link below to reset your password:
${resetLink}

This link will expire in 1 hour.

If you didn't request a password reset, please ignore this email.

Best regards,
Nexus Team
    `;
    
    const info = await sendEmail({ to: email, subject, html, text });
    
    const messageId = (info && (info.messageId || (info.messageIds && info.messageIds[0]))) || 'unknown';
    console.log('✅ Password reset email sent successfully:', messageId);
    
    const isDevelopment = process.env.NODE_ENV !== 'production';
    
    res.json({
      success: true,
      messageId: info.messageId,
      message: 'Password reset email sent successfully',
      resetLink: isDevelopment ? resetLink : undefined
    });
    
  } catch (error) {
    console.error('❌ Error sending password reset email:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to send password reset email',
      details: error.message
    });
  }
});

// Start server (for local development)
if (process.env.NODE_ENV !== 'production') {
  app.listen(PORT, () => {
    console.log(`🚀 Nexus Email Service running on port ${PORT}`);
    console.log(`📧 Brevo configured: ${brevoReady ? 'Yes' : 'No'}`);
    console.log(`🔗 Health check: http://localhost:${PORT}/`);
  });
}

// Export for Vercel serverless
module.exports = app;

// Periodic cleanup of expired OTPs
/**
 * The function `cleanupExpiredOtps` asynchronously cleans up expired OTP entries from a database.
 * @returns The `cleanupExpiredOtps` function is returning a Promise.
 */
async function cleanupExpiredOtps() {
  try {
    if (!db || typeof db.ref !== 'function') return;
    console.log('🧹 Starting OTP cleanup...');
    const snap = await db.ref('otp').once('value');
    const data = snap && typeof snap.val === 'function' ? snap.val() : snap?.val;
    const all = typeof data === 'function' ? data() : data;
    if (!all || typeof all !== 'object') {
      console.log('✅ No OTPs to clean up');
      return;
    }
    const now = Date.now();
    const entries = Object.entries(all);
    let removed = 0;
    await Promise.all(entries.map(async ([key, value]) => {
      if (!value || !value.expiresAt || value.expiresAt <= now) {
        await db.ref(`otp/${key}`).remove();
        removed++;
      }
    }));
    console.log(`🧽 OTP cleanup completed. Removed ${removed} expired entries.`);
  } catch (e) {
    console.error('❌ OTP cleanup failed:', e);
  }
}

setInterval(cleanupExpiredOtps, 5 * 60 * 1000);
setTimeout(cleanupExpiredOtps, 15 * 1000);
